#!/bin/bash

DIST=$1


fuction usage() {
   echo "ERROR: Missing argument."
   echo "$0 <dist>"
   echo "Valid dist: u12, u14, c7"
   exit 1
}

if [ -z "$DIST" ] ; then
   usage
fi

case "$DIST" in
u12)
   ROLE_KVM=kvm-u12.conf
   ROLE_MGMT=cloudstack-mgt-ubuntu12.conf
   ;;
u14)
   ROLE_KVM=kvm-u14.conf
   ROLE_MGMT=cloudstack-mgt-ubuntu14.conf
   ;;
c7)
   ROLE_KVM=kvm-c7.conf
   ROLE_MGMT=cloudstack-mgt-centos7.conf
   ;;
*)
   echo "ERROR: Unsupported role"
   exit 1
   ;;
esac

ln -s --force $ROLE_KVM kvm.conf
ln -s --force $ROLE_MGMT cs.conf

